### ISSUE TITLE
Request Content

### ISSUE THREAD

**Issue by cdreetz** [dolevshor/Azure-OpenAI-Insights#1]
Thank you for making this it looks great so far.  One thing I can't figure out based on the repo or the docs is whether this solution provides logging the actual contents of requests and responses, not just counts and aggregate numbers.  It's the one thing that all Azure OpenAI monitoring solutions don't seem to cover is logging the actual prompts and conversation.  I have worked out a custom solution but continue to be on the lookout for something fully integrated that allows us to monitor how people are using our AI applications, what kinds of things they typically ask, and what kinds of responses they are getting.

**Comment by yodobrin** [comment]
Thanks for your feedback! Prompts and any other applicative information are not logged by the platform. This is by design.
