### ISSUE TITLE
Enabled Diagnostics logs but do not see model level stats displayed in this workbook

### ISSUE THREAD

**Issue by jeevanions** [dolevshor/Azure-OpenAI-Insights#10]
I have taken one of the KQL used in the workbook and ran in the Log analytics workspace. But do not see the logs expected by this query. Did Azure change anything the way the Azure OpenAI logs are captured. For sure I enabled the diagnostis settings routing the logs to Log Analytics workspace.

```
AzureDiagnostics
| where ResourceProvider == "MICROSOFT.COGNITIVESERVICES"
    and Category == "RequestResponse"
| extend properties = parse_json(properties_s)
| extend modelDeploymentName=tostring(properties.modelDeploymentName)
| where OperationName !has "_List"
    and Resource in~ (split("{Resources:label}", ", "))
    and ResultSignature == 200    
    and isnotempty(modelDeploymentName)
| distinct modelDeploymentName
```

**Comment by dolevshor** [comment]
Hi @jeevanions,

`and Resource in~ (split("{Resources:label}", ", "))`

The `{Resources:label}` is the way to use Parameter in Azure Workbook.
You don't need to use it when you run the query in Log Analytics workspace.

You can use this query:

```kql
AzureDiagnostics
| where ResourceProvider == "MICROSOFT.COGNITIVESERVICES"
    and Category == "RequestResponse"
| extend properties = parse_json(properties_s)
| extend modelDeploymentName=tostring(properties.modelDeploymentName)
| where OperationName !has "_List"
   //and Resource in~ (split("{Resources:label}", ", "))
    and ResultSignature == 200    
    and isnotempty(modelDeploymentName)
| distinct modelDeploymentName
```

Please let me know if it solved your issue.

**Comment by dolevshor** [comment]
Hi @jeevanions,

I'm closing this issue.
Please let me know if you have any further question.
