### ISSUE TITLE
Bug: “Provisioned-managed Utilization by Model Name” chart is showing only one model

### ISSUE THREAD

**Issue by UmarMohamedUsman** [dolevshor/Azure-OpenAI-Insights#12]
Even though multiple models have been deployed, “Provisioned-managed Utilization by Model Name” chart is showing only one model. splitBy configuration is missing for PTU Utilization Metric (by Model Name, Model Version, Model Deployment Name, StreamType, Region).

I request to add splitBy configuration and update the workbook. Thanks.

**Comment by dolevshor** [comment]
Hi @UmarMohamedUsman ,

Thanks a lot for your feedback.
Indeed, the "splitBy" dimension configuration was missing.

I fixed it and now it is set properly. (You can use the latest release v1.1)
