### ISSUE TITLE
Insight Tab is not working

### ISSUE THREAD

**Issue by ArpitaisAn0maly** [dolevshor/Azure-OpenAI-Insights#13]
I am trying to use your workbook but insight tab is working. it is not able to get model deployment name . All other tabs are working fine. Only insight tab is not working. I have followed directions from this repo

<img width="705" alt="image" src="https://github.com/user-attachments/assets/0c36104f-a65f-4fdb-89c9-c77dfd3fd7c4">

**Comment by dolevshor** [comment]
Hi @ArpitaisAn0maly ,

Have you enabled diagnostic settings on the AOAI instance/s to send logs to this Log Analytics Workspace?
The Insights tab [is based](https://github.com/dolevshor/Azure-OpenAI-Insights?tab=readme-ov-file#structure) on the logs collected on the Log Analytics Workspace/s.

![image](https://github.com/user-attachments/assets/2dcca3a3-604a-4fe2-8f98-1cc237ec016b)

**Comment by ArpitaisAn0maly** [comment]
Hi @dolevshor Yes I have. I have followed all steps. You can see in my screenshot I have selected log analytics workspace in drop down.

**Comment by dolevshor** [comment]
Hi,

Could you please check this closed issue: https://github.com/dolevshor/Azure-OpenAI-Insights/issues/9

Oldest AOAI API can be the reason as the logs schema was updated.

Please let me know if it's help to solved your issue.

**Comment by dolevshor** [comment]
Hi @ArpitaisAn0maly ,

Any update?
