### ISSUE TITLE
network public access - shows incorrect info - enhancement request

### ISSUE THREAD

**Issue by zenkpr** [dolevshor/Azure-OpenAI-Insights#2]
Thanks for this centralised open ai insights!

i have 2 items.
    1. I have all AI instances with public access disabled and alal of them have private endpoint enabled.But the insight section has discrepancy as updated in screenshot.
    2. the workbook shows other AI services such as face recongiser,text translator..I would need only the Open AI service monitoring.
    3. and lastly, it will be great to capture the deployed model (such as gtp-35,gpt-35-turb,gpt-4 etc with their currently allocated limits (TPM) etc per AI instance ,this will be beneficial for efficient Quota management.

<img width="1284" alt="Screenshot 2024-01-13 at 11 50 21 AM" src="https://github.com/dolevshor/Azure-OpenAI-Insights/assets/25930125/e363718c-641f-4326-93c6-95fc9717c857">
==

**Comment by yodobrin** [comment]
Thanks for the feedback!
1. We will look into this.
2. indeed, aoai has the same type of other cognitive services, we will add a filter for that.
3. let us research this, i am not sure its part of the available metrics or diagnostics.

**Comment by yodobrin** [comment]
1. Corrected with latest version of the workbook
2. The filter now only takes Azure OpenAI kind. 
3. We did not see a simple API that provides this information.

**Comment by zenkpr** [comment]
Thanks, will test out and btw,

we can get the quota info via the following and let me test this out..
https://learn.microsoft.com/en-gb/azure/ai-services/openai/how-to/quota?tabs=rest
https://learn.microsoft.com/en-gb/azure/ai-services/openai/how-to/quota?tabs=rest
