### ISSUE TITLE
Unable to select a log analytics workspace for the insights tab

### ISSUE THREAD

**Issue by CarlosBarichello** [dolevshor/Azure-OpenAI-Insights#3]
After I install the workbook, I navigate to the insights tab and I see that there is no log analytics workspace selected.   I go into edit mode so that I can select one, but there is nothing in the drop down.   How do I get my log analytics workspace to show up in the drop down? 

<img width="230" alt="issue" src="https://github.com/dolevshor/Azure-OpenAI-Insights/assets/21269095/119bdc3a-ac31-49f8-b2f3-a0a8d35a0cb9">

**Comment by dolevshor** [comment]
Hi @CarlosBarichello,
Have you created or do you already have any Log Analytics Workspace in one of your selected Subscriptions?

**Comment by CarlosBarichello** [comment]
Hi @dolevshor.   Thanks for getting back.   The short answer is yes.   But let me give you some additional information.   Perhaps you'll spot something that I need to do differently.

I have two subscriptions.  Let's call them A and B.   Subscription A has the Open AI instance, and it writes to a Log Analytics Workspace in subscription B.  This works great.  When I go to the Log Analytics Workspace, I can see activity.  I did all this before I installed the workbook.

Next, I installed the workbook in subscription B.   When I bring up the workbook, I use the drop downs to select subscription A (which has my Open AI instance.    If I go to the monitor tab, I see information.  However, if I go to the insights tab, I am not able to select the Log Analytics Workspace from the drop-down menu because I don’t see it there.    

What logic is used to populate the log analytics workspace drop down in the insights tab?

**Comment by dolevshor** [comment]
Hi @CarlosBarichello,

First, thank you for the clarification and excellent explanation.
Now I understand why you didn't see the Log Analytics Workspace.
This is an excellent point that we will consider if it is right to change it or keep it simple.

<ins>The logic</ins>
To keep it simple, the 'Subscriptions' filter affects the OpenAI instance **and** the Log Analytics Workspace.
We can split the 'Subscriptions' filter into 2 separate filters, one for OpenAI Instances and the other for the Log Analytics Workspace.

**Comment by yodobrin** [comment]
My 2 cents here: select both subscriptions in the filter and use the filter for your endpoints when selecting the monitored endpoints. As of now, I see no reason to add too much filter logic.

**Comment by CarlosBarichello** [comment]
@dolevshor , @yodobrin.  Thanks for the information.  I just needed to understand why my Log Analytics Workspace was not showing in the drop down of the insights tab:  That is clear now.   I appreciate your help.
