### ISSUE TITLE
Metrics show "Error retrieving Data"

### ISSUE THREAD

**Issue by robertkossendey** [dolevshor/Azure-OpenAI-Insights#4]
Thanks for the excellent workbook! 
All of the monitoring graphs show "Error retrieving Data," though. Do you have any ideas on how to solve that? 
It might be workbook-unrelated, though; I am not an Azure expert but an AWS guy.

**Comment by dolevshor** [comment]
Hi @robertkossendey,
First, thanks for the kind words and we happy to hear you find this workbook useful.
I saw that you closed the issue, did you find a solution? Please let us know if you need help and feel free to open new issues/PRs.

**Comment by robertkossendey** [comment]
Hi @dolevshor! I did not do anything 😅 after some hours, the data appeared. The same problem occurred in the dashboards in the actual OpenAI service.
