### ISSUE TITLE
'extend' operator: Failed to resolve scalar expression named 'properties_s'

### ISSUE THREAD

**Issue by felix-dksh** [dolevshor/Azure-OpenAI-Insights#5]
Hi, 

I have created and put the provided workbook, but faced this issue in Monitor after assigned  Log Analytics Workspace.

`'extend' operator: Failed to resolve scalar expression named 'properties_s' on all metrics under Insights section.`

[Screenshot](https://1drv.ms/i/s!AqVFcm8Q8KFxhzheC-TB717k3_8a?e=US4K1t)

**Comment by dolevshor** [comment]
Hi @felix-dksh,

The insights part is based on logs.
To view them you must enable their collection via diagnostic settings.

Please read this note:
![image](https://github.com/dolevshor/Azure-OpenAI-Insights/assets/69309933/479fcce3-01cb-4350-8b1f-cd2da93c9653)

Did you [configure diagnostic settings](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/monitoring#configure-diagnostic-settings) to your Azure OpenAI Instances?

**Comment by piizei** [comment]
I'm having the same problem, and I have following diagnostic settings enabled and exported to LAW:
AllMetrics = true
allLogs = true
Send to Log Analytics Workspace = true

If I check the diagnostic logs directly from LAW I can see caller-ip's and things, but not the column properties_s.

**Comment by piizei** [comment]
Actually the column appeared some time later, and the workbook seems to work.
