### ISSUE TITLE
ISSUE - Azure OpenAI Insights tab does not load data from log analytics

### ISSUE THREAD

**Issue by JQUINONES82** [dolevshor/Azure-OpenAI-Insights#8]
When selecting a Log Analytics Workspace to load Insights, the queries just spin and does not load any data.

All recommended log analytics settings are enabled but workbook can not load the data

https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/monitoring#configure-diagnostic-settings

![openai image](https://github.com/dolevshor/Azure-OpenAI-Insights/assets/23418730/b3fd685d-7eb3-4a3f-9910-f5ed2a878e12)

**Comment by dolevshor** [comment]
Hi @JQUINONES82,

Can you please share the whole dashboard (including the filters), this will help me to understand why it's not loading for you.

**Comment by dolevshor** [comment]
Hi @JQUINONES82 ,

Any update? (Please let me know before closing the issue)

**Comment by JQUINONES82** [comment]
![image](https://github.com/dolevshor/Azure-OpenAI-Insights/assets/23418730/ec6feb19-e716-46b4-a802-baefecc9d026)
First two tabs work.  THis is what Im using at the moment.  Sorry as I was away

**Comment by JQUINONES82** [comment]
IT basically just spins and never loads the data for the insights tab.

**Comment by dolevshor** [comment]
@JQUINONES82,

The filters are based on logs. (You need to enable Diagnostic Settings on the AOAI instance).
This behavior is when you have no logs.

You can check if you have logs in your Log Analytics Workspace with this KQL query:

AzureDiagnostics | where ResourceProvider == "MICROSOFT.COGNITIVESERVICES" and Category == "RequestResponse"

When you have logs, the filters are loaded successfully.

![image](https://github.com/dolevshor/Azure-OpenAI-Insights/assets/69309933/8f0d21da-de33-4f46-99b2-83e51c699cba)

**Comment by JQUINONES82** [comment]
![image](https://github.com/dolevshor/Azure-OpenAI-Insights/assets/23418730/9c718fb4-d570-4add-b816-21d2a8e266e1)
So we have about 2106 entries in the logs
Again the thing just spins.  Do I need app analytics or just need to send all data as it is currently set like this
![image](https://github.com/dolevshor/Azure-OpenAI-Insights/assets/23418730/70def9ca-b54e-48d9-a7ec-0a1d2d8785bd)

**Comment by JQUINONES82** [comment]
I am calling the same log analytics configured here in your workbook but the third tab never loads.

**Comment by JQUINONES82** [comment]
Any updates?
