### ISSUE TITLE
Re Opening from Issue 8

### ISSUE THREAD

**Issue by JQUINONES82** [dolevshor/Azure-OpenAI-Insights#9]
There is data from log analytics but it does not work for the Insights Tab

I can clearly see the logs and provided a count

ISSUE - Azure OpenAI Insights tab does not load data from log analytics #8

Can you explain why it can not get to the log analytics data?

**Comment by dolevshor** [comment]
Hi @JQUINONES82,

My apologies, I missed your message.
I would be happy to set a short call together to understand the reason and solved your issue.
Please let me know when is convenience for you.

**Comment by melkor54248** [comment]
I'm having the same issue

**Comment by JQUINONES82** [comment]
I had the great pleasure of working with Dolev.  We did a working session and found a solution for myself.  Maybe it will work for you.

Log into your log analytics work space and check the columns for your Open AI Instances.

See if you have ResultSignature or resultSignature_d.

I had resultSignature_d.

We updated his workbook to find all instances that contained ResultSignature == 200 to resultSignature_d == 200.  I just did a find and replace on the json workbook code and redeployed.  Then it worked for me.  There is a way to edit the workbook and test for each part, but this is how I fixed it for the third tab.   See if it works for you.

**Comment by dolevshor** [comment]
@JQUINONES82 Thanks for your collaboration. I'm glad we found the reason why you couldn't see the logs and now you can use the Workbook.

Just to clarify that the root-cause of the issue was by using an old Azure OpenAI Instance API.
- In the latest APIs the column name is _ResultSignature_.
- In Old APIs is _resultSignature_d_.

**Comment by dolevshor** [comment]
> I'm having the same issue

@melkor54248 Please update if you were able to solve the problem. (My suggestion is to first check you AOAI API).
